language: python
python:
    - "2.7"
env: PGVERSION=9.2
dist: trusty
sudo: required
cache: pip
env:
    - CKANVERSION=2.7
services:
    - redis-server
    - postgresql
install:
    - pip install --no-cache-dir git+https://github.com/ViderumGlobal/ckanext-spatial.git@ckan-2.7#egg=ckanext-spatial
    - pip install --no-cache-dir -r https://raw.githubusercontent.com/ckan/ckanext-spatial/master/pip-requirements.txt
    - bash bin/travis-build.bash
    - pip install flake8==3.5.0
script:
    - sh bin/travis-run.sh
    - flake8 ./ckanext/nextgeossharvest --exclude ./ckanext/nextgeossharvest/harvesters/opensearch_example.py,./ckanext/nextgeossharvest/harvesters/cmems.py,./ckanext/nextgeossharvest/lib/cmems_base.py,./ckanext/nextgeossharvest/harvesters/gome2.py,./ckanext/nextgeossharvest/lib/gome2_base.py,./ckanext/nextgeossharvest/harvesters/itag.py --ignore E127,E128

