CMEMS_IGNORE_LIST = [
        "StartTime",
        "StopTime",
        "downloadLink",
        "thumbnail",
        "downloadLinkEase",
        "downloadLinkPolstere",
        "size"
]

CMEMS_IGNORE_DICT = {
    "METOFFICE-GLO-SST-L4-NRT-OBS-SST-V2": CMEMS_IGNORE_LIST,
    "METNO-GLO-SEAICE_CONC-NORTH-L4-NRT-OBS": CMEMS_IGNORE_LIST,
    "METNO-GLO-SEAICE_CONC-SOUTH-L4-NRT-OBS": CMEMS_IGNORE_LIST,
    "ARCTIC_ANALYSIS_FORECAST_PHYS_002_001_A": CMEMS_IGNORE_LIST,
    "SEALEVEL_GLO_PHY_L4_NRT_OBSERVATIONS_008_046": CMEMS_IGNORE_LIST,
    "GLOBAL_ANALYSIS_FORECAST_PHY_001_024": CMEMS_IGNORE_LIST,
    "MULTIOBS_GLO_PHY_NRT_015_003": CMEMS_IGNORE_LIST
}