FSSCAT_IGNORE_LIST = [
        "family_name",
        "instrument_name",
        "product_type",
        "creation_time",
        "class",
        "baseline",
        "scheme"
]

FSSCAT_IGNORE_DICT = {
    "FSSCAT_GRF_L1C_SCI": FSSCAT_IGNORE_LIST,
    "FSSCAT_GRF_L1B_CAL": FSSCAT_IGNORE_LIST,
    "FSSCAT_GRF_L1B_SCI": FSSCAT_IGNORE_LIST,
    "FSSCAT_GRF_L2__SIE": FSSCAT_IGNORE_LIST,
    "FSSCAT_GRF_L3__SIE": FSSCAT_IGNORE_LIST,
    "FSSCAT_MWR_L1B_SCI": FSSCAT_IGNORE_LIST,
    "FSSCAT_MWR_L1C_SCI": FSSCAT_IGNORE_LIST,
    "FSSCAT_MWR_L2A_TB_": FSSCAT_IGNORE_LIST,
    "FSSCAT_MWR_L2B_SIT": FSSCAT_IGNORE_LIST,
    "FSSCAT_MWR_L2B_SM_": FSSCAT_IGNORE_LIST,
    "FSSCAT_MWR_L3__TB_": FSSCAT_IGNORE_LIST,
    "FSSCAT_MWR_L3__SIT": FSSCAT_IGNORE_LIST,
    "FSSCAT_MWR_L3__SM_": FSSCAT_IGNORE_LIST,
    "FSSCAT_MWR_L4__SM_": FSSCAT_IGNORE_LIST,
    "FSSCAT_HPS_L1C_SCI": FSSCAT_IGNORE_LIST,
    "FSSCAT_HPS_L2__RDI": FSSCAT_IGNORE_LIST,
    "FSSCAT_SYN_L4__SM_": FSSCAT_IGNORE_LIST
}
