GOME2_IGNORE_LIST = [
        "StartTime",
        "StopTime"
]

GOME2_IGNORE_DICT = {
    "METOP_A_GOME2_O3": GOME2_IGNORE_LIST,
    "METOP_A_GOME2_NO2": GOME2_IGNORE_LIST,
    "METOP_A_GOME2_TropNO2": GOME2_IGNORE_LIST,
    "METOP_A_GOME2_SO2": GOME2_IGNORE_LIST,
    "METOP_A_GOME2_SO2mass": GOME2_IGNORE_LIST
}