from sentinel import SENTINEL_IGNORE_DICT
from probav import PROBAV_IGNORE_DICT
from gome2 import GOME2_IGNORE_DICT
from modis import MODIS_IGNORE_DICT
from foodsecurity import FOODSECURITY_IGNORE_DICT

IGNORE_LIST = {}

IGNORE_LIST.update(SENTINEL_IGNORE_DICT)
IGNORE_LIST.update(PROBAV_IGNORE_DICT)
IGNORE_LIST.update(GOME2_IGNORE_DICT)
IGNORE_LIST.update(MODIS_IGNORE_DICT)
IGNORE_LIST.update(FOODSECURITY_IGNORE_DICT)