from sentinel import SENTINEL_IGNORE_DICT
from probav import PROBAV_IGNORE_DICT
from gome2 import GOME2_IGNORE_DICT
from modis import MODIS_IGNORE_DICT
from foodsecurity import FOODSECURITY_IGNORE_DICT
from deimosimg import DEIMOSIMG_IGNORE_DICT
from plan4all import PLAN4ALL_IGNORE_DICT
from cmems import CMEMS_IGNORE_DICT
from ebvs import EBVS_IGNORE_DICT
from vitocgs import VITOCGS_IGNORE_DICT
from simocean import SIMOCEAN_IGNORE_DICT
from ebas import EBAS_IGNORE_DICT
from epos import EPOS_IGNORE_DICT
from gdacs import GDACS_IGNORE_DICT
from saeon import SAEON_IGNORE_DICT
from scent import SCENT_IGNORE_DICT
from landsat8 import LANDSAT8_IGNORE_DICT
from coldregions import COLDREGIONS_IGNORE_DICT
from satcen_better import SATCEN_BETTER_IGNORE_DICT

IGNORE_LIST = {}

IGNORE_LIST.update(SENTINEL_IGNORE_DICT)
IGNORE_LIST.update(PROBAV_IGNORE_DICT)
IGNORE_LIST.update(GOME2_IGNORE_DICT)
IGNORE_LIST.update(MODIS_IGNORE_DICT)
IGNORE_LIST.update(FOODSECURITY_IGNORE_DICT)
IGNORE_LIST.update(DEIMOSIMG_IGNORE_DICT)
IGNORE_LIST.update(PLAN4ALL_IGNORE_DICT)
IGNORE_LIST.update(CMEMS_IGNORE_DICT)
IGNORE_LIST.update(EBVS_IGNORE_DICT)
IGNORE_LIST.update(VITOCGS_IGNORE_DICT)
IGNORE_LIST.update(SIMOCEAN_IGNORE_DICT)
IGNORE_LIST.update(EBAS_IGNORE_DICT)
IGNORE_LIST.update(EPOS_IGNORE_DICT)
IGNORE_LIST.update(GDACS_IGNORE_DICT)
IGNORE_LIST.update(SAEON_IGNORE_DICT)
IGNORE_LIST.update(SCENT_IGNORE_DICT)
IGNORE_LIST.update(LANDSAT8_IGNORE_DICT)
IGNORE_LIST.update(COLDREGIONS_IGNORE_DICT)
IGNORE_LIST.update(SATCEN_BETTER_IGNORE_DICT)
