SATCEN_BETTER_IGNORE_LIST = []

SATCEN_BETTER_IGNORE_DICT = {
    "S1_ACD_SATCEN_BETTER": SATCEN_BETTER_IGNORE_LIST,
    "S2_MINERAL_INDEX_SATCEN_BETTER": SATCEN_BETTER_IGNORE_LIST,
    "S2_VEGETAION_MASK_SATCEN_BETTER": SATCEN_BETTER_IGNORE_LIST
}