SENTINEL_IGNORE_LIST = [
        "FamilyName",
        "InstrumentName",
        "ProductClass",
        "uuid",
        "AcquisitionType",
        "noa_expiration_date",
        "Filename",
        "size",
        "thumbnail",
        "summary",
        "scihub_download_url",
        "scihub_product_url",
        "scihub_manifest_url",
        "scihub_thumbnail",
        "noa_download_url",
        "noa_product_url",
        "noa_manifest_url",
        "noa_thumbnail",
        "code_download_url",
        "code_product_url",
        "code_manifest_url",
        "code_thumbnail",
        "StartTime",
        "StopTime"
]

SENTINEL_IGNORE_DICT = {
    "SENTINEL1_L1_SLC": SENTINEL_IGNORE_LIST,
    "SENTINEL1_L1_GRD": SENTINEL_IGNORE_LIST,
    "SENTINEL1_L2_OCN": SENTINEL_IGNORE_LIST,
    "SENTINEL2_L1C": SENTINEL_IGNORE_LIST,
    "SENTINEL2_L2A": SENTINEL_IGNORE_LIST,
    "SENTINEL3_SRAL_L1_CAL": SENTINEL_IGNORE_LIST,
    "SENTINEL3_SRAL_L1_SRA": SENTINEL_IGNORE_LIST,
    "SENTINEL3_SRAL_L2_LAN": SENTINEL_IGNORE_LIST,
    "SENTINEL3_SRAL_L2_WAT": SENTINEL_IGNORE_LIST,
    "SENTINEL3_OLCI_L1_EFR": SENTINEL_IGNORE_LIST,
    "SENTINEL3_OLCI_L1_ERR": SENTINEL_IGNORE_LIST,
    "SENTINEL3_OLCI_L2_LFR": SENTINEL_IGNORE_LIST,
    "SENTINEL3_OLCI_L2_LRR": SENTINEL_IGNORE_LIST,
    "SENTINEL3_SLSTR_L1_RBT": SENTINEL_IGNORE_LIST,
    "SENTINEL3_SLSTR_L2_LST": SENTINEL_IGNORE_LIST,
    "SENTINEL3_SY_1_MISR": SENTINEL_IGNORE_LIST,
    "SENTINEL3_SY_2_SYN": SENTINEL_IGNORE_LIST,
    "SENTINEL3_SY_2_VGP": SENTINEL_IGNORE_LIST,
    "SENTINEL3_SY_2_VGK": SENTINEL_IGNORE_LIST,
    "SENTINEL3_SY_2_VG1": SENTINEL_IGNORE_LIST,
    "SENTINEL3_SY_2_V10": SENTINEL_IGNORE_LIST,
    "SENTINEL5P_OFFL_L1B": SENTINEL_IGNORE_LIST,
    "SENTINEL5P_OFFL_L2": SENTINEL_IGNORE_LIST,
    "SENTINEL5P_NRTI_L2": SENTINEL_IGNORE_LIST,
    "SENTINEL5P_RPRO_L2": SENTINEL_IGNORE_LIST
}