SIMOCEAN_IGNORE_LIST = [
        "Limitations On Public Access",
        "LimitationsOnPublicAccess",
        "CreationTime",
        "Responsible Party",
        "ResponsibleParty",
        "Metadata Date",
        "MetadataDate",
        "StartTime",
        "StopTime"
]

SIMOCEAN_IGNORE_DICT = {
    "SIMOCEAN_SURFACE_WIND_FORECAST_FROM_AROME": SIMOCEAN_IGNORE_LIST,
    "SIMOCEAN_CLOUDINESS_FORECAST_FROM_AROME": SIMOCEAN_IGNORE_LIST,
    "SIMOCEAN_SURFACE_CURRENTS_FROM_HF_RADAR": SIMOCEAN_IGNORE_LIST,
    "SIMOCEAN_NEARSHORE_SEA_STATE_FORECAST_FROM_SWAN": SIMOCEAN_IGNORE_LIST,
    "SIMOCEAN_PORT_SEA_STATE_FORECAST_FROM_SMARTWAVE": SIMOCEAN_IGNORE_LIST,
    "SIMOCEAN_DATA_FROM_MULTIPARAMETRIC_BUOYS": SIMOCEAN_IGNORE_LIST,
    "SIMOCEAN_TIDAL_DATA": SIMOCEAN_IGNORE_LIST,
    "SIMOCEAN_SURFACE_FORECAST_FROM_HYCOM": SIMOCEAN_IGNORE_LIST,
    "SIMOCEAN_SEA_SURFACE_WIND_FORECAST": SIMOCEAN_IGNORE_LIST,
    "SIMOCEAN_MEAN_SEA_LEVEL_PRESSURE_FORECAST": SIMOCEAN_IGNORE_LIST,
    "SIMOCEAN_SEA_SURFACE_TEMPERATURE_FORECAST": SIMOCEAN_IGNORE_LIST,
    "SIMOCEAN_AIR_SURFACE_TEMPERATURE_FORECAST": SIMOCEAN_IGNORE_LIST,
    "SIMOCEAN_SEA_WAVE_DIRECTION_FORECAST": SIMOCEAN_IGNORE_LIST,
    "SIMOCEAN_SEA_WAVE_PERIOD_FORECAST": SIMOCEAN_IGNORE_LIST,
    "SIMOCEAN_PRECIPITATION_FORECAST_FROM_AROME": SIMOCEAN_IGNORE_LIST,
    "SIMOCEAN_SIGNIFICANT_WAVE_HEIGHT_FORECAST": SIMOCEAN_IGNORE_LIST
}